# vim:set expandtab shiftwidth=4 filetype=yaml:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/header-metadata.nvim.git
# ::: :/.github/workflows/commitlint.yaml
#
#

name: Lint Commit Messages

on:
    pull_request:

permissions:
    contents: read
    pull-requests: read

jobs:
    commitlint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - uses: wagoid/commitlint-github-action@v6
